# Default values for horovod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

useHostNetwork: false
hostNetworkInterface: ""
useHostPID: false

commandline:
  args:
    {% for arg in NAUTA.CommandLine %}
    - {{ arg }}
    {% endfor %}

ssh:
  port: 32222
  useSecrets: True

image:
  clusterRepository: {{ NAUTA.ExperimentImage }}
  pullPolicy: IfNotPresent

workersCount: 3

volumeMounts:
  - name: input-home
    mountPath: /mnt/input/home
    readOnly: True
  - name: input-public
    mountPath: /mnt/input/root
    readOnly: True
  - name: output-home
    mountPath: /mnt/output/home
  - name: output-public
    mountPath: /mnt/output/root
    readOnly: True
  - name: output-public
    mountPath: /mnt/output/root/public
    subPath: public
  - name: input-public
    mountPath: /mnt/input/root/public
    subPath: public

volumes:
  - name: input-home
    persistentVolumeClaim:
      claimName: input-home
  - name: input-public
    persistentVolumeClaim:
      claimName: input-public
  - name: output-home
    persistentVolumeClaim:
      claimName: output-home
  - name: output-public
    persistentVolumeClaim:
      claimName: output-public

worker:
  podManagementPolicy: Parallel

master:
  env:
    - name: HOROVOD_TIMELINE
      value: "/mnt/output/experiment/timeline.json"
    - name: OMP_NUM_THREADS
      value: "20"
runKind: "training"

experimentName: {{ NAUTA.ExperimentName }}
registryPort: {{ NAUTA.RegistryPort }}

podCount: 1

resources:
  requests:
    cpu: 38 # Minimal number of logical processors requested
    memory: 189.4Gi
  limits:
    cpu: 38 # Maximal number of logical processors requested
    memory: 189.4Gi

cpu: null
memory: null

# Number of physical processors that will be used by Horovod
cpus: 20

processesPerNode: 2

cpu_fraction: 1
memory_fraction: 1
